services:
  - type: web
    name: mon-projet-laravel
    env: docker
    plan: free
    branch: old-version
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://s228-2.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ydaydy.h.filess.io
      - key: DB_PORT
        value: 3307
      - key: DB_DATABASE
        value: S228_islandsell
      - key: DB_USERNAME
        value: S228_islandsell
      - key: DB_PASSWORD
        value: da506473c09b7ca4120a02b7953ff991b6d5099d
        sync: false
      - key: SESSION_DRIVER
        value: file


