services:
  - type: web
    name: mon-projet-laravel
    env: docker
    plan: free
    branch: develop
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://mon-projet-laravel.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ton-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: ta-base
      - key: DB_USERNAME
        value: ton-user
      - key: DB_PASSWORD
        sync: false


